CREATE TABLE `user_details` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(255) NOT NULL,
  `mobile_number` VARCHAR(20) NOT NULL,
  `email` VARCHAR(20) DEFAULT NULL,
  `gender` ENUM('MALE','FEMALE') DEFAULT 'MALE',
  `created_by` INT NOT NULL,
  `registered_at` DATETIME DEFAULT CURRENT_TIMESTAMP,
  `is_active` INT NOT NULL DEFAULT '1',
  `is_whatsApp` ENUM('Yes','No') DEFAULT 'Yes',
  `last_login_at` DATETIME DEFAULT NULL,
  `updated_at` DATETIME DEFAULT NULL,
  PRIMARY KEY (`id`)
) ENGINE=INNODB DEFAULT CHARSET=utf8mb4;


CREATE TABLE `user_token` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `token` VARCHAR(2500) NOT NULL,
  `user_id` INT NOT NULL,
  PRIMARY KEY (`id`)
) ENGINE=INNODB DEFAULT CHARSET=utf8mb4;


CREATE TABLE `user_mapping` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `user_id` INT NOT NULL,
  `user_type` INT NOT NULL,
  PRIMARY KEY (`id`)
) ENGINE=INNODB DEFAULT CHARSET=utf8mb4;


CREATE TABLE `user_types` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `user_type` VARCHAR(20) NOT NULL,
  PRIMARY KEY (`id`)
) ENGINE=INNODB AUTO_INCREMENT=1 DEFAULT CHARSET=utf8mb4;

CREATE TABLE `mark_sheet` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(25) DEFAULT NULL,
  `gender` VARCHAR(10) DEFAULT NULL,
  `age` INT DEFAULT NULL,
  `section` VARCHAR(10) CHARACTER SET utf8mb4 DEFAULT NULL,
  `marks` JSON DEFAULT NULL,
  `creation_time` DATETIME DEFAULT CURRENT_TIMESTAMP,
  `status` ENUM('New','Done','Failed','Inprogress') DEFAULT 'New',
  PRIMARY KEY (`id`)
) ENGINE=INNODB DEFAULT CHARSET=utf8mb4;
